# Generated by Django 5.2.15 on 2026-06-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='gst_note',
            field=models.CharField(blank=True, default='Exclusive of 18% GST', help_text="Shown next to the price, e.g. 'Exclusive of 18% GST'.", max_length=120),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='headline',
            field=models.CharField(blank=True, help_text="Short tagline shown under the name, e.g. 'Technology & business leader, 34+ years'.", max_length=200),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo. (On free hosting, prefer photo_url until persistent storage is set up.)', null=True, upload_to='mentor_photos/'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Alternative: a hosted image link. Used if no uploaded photo is present.'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text="Mentor's rate per session, in INR (exclusive of GST).", max_digits=10),
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('intro', models.TextField(blank=True, help_text='Optional sentence shown under the heading.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='profiles.mentorprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profiles.profilesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
