# Generated by Django 5.2.15 on 2026-06-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mentorprofile_gst_note_mentorprofile_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesectionitem',
            name='section',
        ),
        migrations.CreateModel(
            name='ProfilePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('expertise', 'Core Industry Expertise'), ('focus', 'Mentorship Focus Areas')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='profiles.mentorprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ProfileSection',
        ),
        migrations.DeleteModel(
            name='ProfileSectionItem',
        ),
    ]
