# Generated by Django 5.2.15 on 2026-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profilesectionitem_section_profilepoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='behance_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
