# Generated by Django 5.2.15 on 2026-08-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_menteeprofile_behance_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='availability_note',
            field=models.CharField(blank=True, default='', help_text="Free-text description of when this mentor is generally available, e.g. 'Weekday evenings, IST'.", max_length=240),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='credentials',
            field=models.TextField(blank=True, default='', help_text="Certifications, degrees, or other credentials, e.g. 'MBA — IIM Ahmedabad; PMP certified'."),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='pending_identity_changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='pending_review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
