# Generated by Django 5.2.15 on 2026-06-10 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if a user submitted this rather than an admin.')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved interests are selectable/visible. Custom ones start unapproved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty to make this a top-level category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='interests.interest')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_name_per_parent')],
            },
        ),
    ]
