# Generated by Django 5.2.15 on 2026-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=64),
        ),
    ]
