# Generated by Django 5.2.15 on 2026-08-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='The staff member who archived this account (most recently).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
