# Generated by Django 5.2.15 on 2026-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_is_refunded_booking_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_1h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
