# Generated by Django 5.2.15 on 2026-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_reminder_1h_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
