# Generated by Django 5.2.15 on 2026-07-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_availabilityslot_is_confirmed_weeklyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meet_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='suggested_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_bookings', to='bookings.availabilityslot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('awaiting_approval', 'Awaiting mentor approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('declined', 'Declined by mentor')], default='pending_payment', max_length=20),
        ),
    ]
