# Generated by Django 5.2.15 on 2026-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_approval_due_at_booking_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('awaiting_approval', 'Awaiting mentor approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('declined', 'Declined by mentor'), ('no_show', 'No-show')], default='pending_payment', max_length=20),
        ),
    ]
